### ISSUE TITLE
重置单元

### ISSUE THREAD

**Issue by qqqq0206** [SSmJaE/MyTamperMonkeyScripts#1]
您好：
     请问单元里面显示二维码的 有办法重置单元吗

**Comment by SSmJaE** [comment]
> 您好：
> 请问单元里面显示二维码的 有办法重置单元吗

welearn的？你可以用WELearnToSleep试试

**Comment by qqqq0206** [comment]
好 谢谢&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SSmJaE/MyUserScripts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月9日(星期六) 凌晨0:03
收件人:&nbsp;"SSmJaE/MyUserScripts"<MyUserScripts@noreply.github.com&gt;;
抄送:&nbsp;"耿庆龙"<1486959154@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SSmJaE/MyUserScripts] 重置单元 (#1)





  
您好：
 请问单元里面显示二维码的 有办法重置单元吗
  
welearn的？你可以用WELearnToSleep试试
